---
sources:
  go: true
source_path: pkg
allowed:
  - mit
  - apache-2.0
  - mpl-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
reviewed:
  go:
    - golang.org/x/**/* # bsd-style
    - github.com/magiconair/properties  # bsd-3-clause
    - github.com/sagikazarmark/slog-shim  # BSD-3-Clause Revised
    - github.com/gogo/protobuf/*  # apache-2.0
    - gopkg.in/inf.v0 # apache-2.0
    - gopkg.in/yaml.v2 # apache-2.0
    - sigs.k8s.io/**/* # apache-2.0
    - k8s.io/**/* # apache-2.0
